blinklabs-io/nview

- config.go
- go.mod
- go.sum
- main.go
Support configuration via environment variables.
- Import `envconfig`
- Create a Config struct with a PrometheusConfig member
- Config Prometheus host via `PROM_HOST` environment variable
- Config Prometheus port via `PROM_PORT` environment variable
- Create a `globalConfig` Config object and `GetConfig()` to fetch it
- Create a `LoadConfig()` to initialize `globalConfig`
- Update first row to display an assembled Prometheus metrics URL for a cardano-node using a `tview.TextView`
> feat: config from environment

- config.go
- main.go
Convert processed Prometheus data JSON into a Go struct.
- Import `math`
- Update text view on `prom2json()` error
- Create a `Metrics` struct
- Unmarshal prom2json result bytes into `metrics`
- Create a `timeLeft(seconds)` method to convert seconds to string
- Create a stubbed `uptimes` value of 0
- Display calculated uptime string
- Display epoch number taken from `metrics.EpochNum`
> feat: json unmarshal to struct

- config.go
- main.go
Change our main Prometheus TextView into a Table.
- Add an AppConfig member to Config struct
- Configure display name via `NODE_NAME` environment variable
- Set default `Config.App.NodeName` to "Cardano Node"
- Validate that `Config.App.NodeName` is <= 19 characters
- Enable dynamic colors on `text` and update text output
- Support `esc` key to quit
- Add `headerText` to contain our header
- Add `promTable` to contain our Prometheus table
- Refactor `Metrics` collection into `getPromMetrics()`
- Refactor `getPromText()` to use `getPromMetrics()`
- Create `getPromTable()` to use `getPromMetrics()`
- Initialize `promTable` using `getPromTable()` function
- Use `promTable` instead of `promText` in our main Flex
> feat: table

- main.go
Removes extra display section and displays stubbed resources.
- Change main Flex w/ `text` and a blank Box to display just `text`
- Uncomment `threeCol2ValueWidth` and `threeCol3ValueWidth` calculations
- Update layout spacing to use calculated widths
- Add metrics display for NODE RESOURCE USAGE
- Calculate `Mem (Live)`/`Mem (Heap)`
- Stub `CPU (sys)` and `Mem (RSS)`
> feat: resources section

- .github/workflows/ci-docker.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/publish.yml
- Dockerfile
- Makefile
- README.md
- config.go
- main.go
Create GitHub Actions workflows for testing and publishing.
- Docker CI workflow to build container images for `linux/amd64` and `linux/arm64`
- Conventional Commits workflow to enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- golangci workflow to run `golangci-lint` and `go test` on a matrix of Golang versions and platforms
- Go: 1.18, 1.19
- Platform: Ubuntu, MacOS
- Publish workflow to create GitHub releases, container images, and binaries
- Images created and published on merge to `main` or a matching (`v*.*.*`) git tag
- Docker Hub: `blinklabs/nview` for `linux/amd64` and `linux/arm64`
- GitHub Container Registry: `ghcr.io/blinklabs-io/nview` for `linux/amd64` and `linux/arm64`
- Binaries built for a matrix of platforms and architectures
- Platform: …
> feat: devops

- main.go
Fixes errors reported by `golangci-lint` tests in our GitHub Actions workflows.
- Move second newline to epoch `sb.WriteString` instead of using a second call
- Save context addition to http request before making request to fix timeout
> fix: save output from request context

- config.go
- main.go
Create an info page.
- Support setting display network name via `NETWORK` environment variable
- Move footer text from global `footerText`
- Track the currently active page using `active` global variable
- Stub Role and Version in `headerText`
- Support `h` key for navigating to main page
- Support `i` key for navigating to info page
- Clear and set `footerText` on key press
- Conditionally clear and set `text` in our refresh loop
- Move `uptimes` to a global
- Only update `uptimes` if we get a `createTime` from the `cardano-node` process
- Create `getInfoText()` to return the info page text
> feat: info page

- config.go
- go.mod
- main.go
Configure the maximum number of retry attempts on failures and add initial terminal size detection.
- Import `terminal`
- Support configuring retries via `RETRIES` environment variable
- Create `populateShelleyTransEpoch()` to populate Shelley Hard Fork Combinator epoch number
- Support overriding Shelley transition epoch via `SHELLEY_TRANS_EPOCH` environment variable
- Convert `uint` to `uint32` to be explicit as `uint` changes based on platform
- Update `globalConfig` with ShelleyTransEpoch
- Configure main `text` Flex item as having focus, allowing scrolling
- Create `getTestText()` for testing upcoming features
- Fetch network connection peers via `getProcessMetrics()` in `getTestText()`
- Update `getProcessMetrics()` to use `process.NewProcessWithContext()`
> feat: retries and terminal size

- main.go
Fetch external IP address using DNS resolution and begin peer processing.
- Import `net`
- Move `role` to a global variable for later use
- Create a local `net.Resolver` using `resolver1.opendns.com:53`
- Lookup IPv4 address for `myip.opendns.com` to get external IP address
- Process `peersIn` and add non-local peers to `peersFiltered` []string
- Process connections for non-P2P nodes
> feat: dns and peers in

- .github/dependabot.yml
- .github/workflows/auto-assign.yml
- CODEOWNERS
- CODE_OF_CONDUCT.md
- main.go
Configure more CI, set role to Core if we have upcoming blocks, and auto assign issues.
- Configure @dependabot automatic weekly version update Pull Requests
- Configure an Auto Assign workflow to assign myself issues
- Create a `CODEOWNERS` file for Pull Request approval list
- Copied `CODE_OF_CONDUCT.md` from github/docs
- Process outbound peers on test page
> feat: set role and display outbound peers

- config.go
- env.go
- main.go
Calculate the current tip reference and determine any local diff.
- Create a `ByronGenesisConfig` to hold Byron era infomation
- Create `populateByronGenesis()` to populate `ByronGenesisConfig` with static defaults
- Improve error handling around unsupported named networks
- Import `localstatequery` in env.go
- Create `getEpoch()` to calculate current epoch from current second
- Create `getSlotTipRef()` to calculate current slot number from current second
- Create `slotInterval()` stub function
- Create `timeUntilNextEpoch()` to calculate time to next epoch from current second
- Refresh data on test page in main loop
- Calculate current epoch progress on test page (still work in progress)
- Update main display to show values for `Tip (ref)` and `Tip (diff)`
> feat: get tip ref and calculate tip diff

- config.go
- env.go
- main.go
Tighten the layout to match gLiveView and fit in smaller terminals.
- Update `slotInterval()` to give proper output
- Update spacing in various *Config structs for readability
- Force `uint64` return on env.go functions
- Update static text for header's node version and revision for node v8.0.0
- Add more debugging for the epoch progress and time left calculations
- Fix `threeColWidth` to use correct value from gLiveView
- Fix `tipDiff` comparison against `slotInterval()`
- Fix `syncProgress` calculation and display
- Begin "Core" section for Block Producer statistics
> feat: tighten layout

- config.go
- env.go
- main.go
Display a epoch progress bar and fix tip ref and diff.
- Set Config.Node.ShelleyTransEpoch to `-1` by default
- Split up `timeUntilNextEpoch()` calculations, which is still failing to give correct results
- Add epoch progress bar to main and test pages
- Add a Byron era length debug display to test page
- Support Byron era epochs in epoch progress displays
- Fix a typo in the Core section on main
> feat: epoch progress bar

- env.go
- main.go
Move peer analysis code from test page to its own page.
- Create `getCurrentKESPeriod()` to calculate from tip ref
- Rename `getPromText()` to `getHomeText()` to reflect correct use
- Remove center alignment on header text
- Calculate header padding from input lengths
- Support `p` to display peer analysis
- Replace `r` with `p` in default footer text
- Increase dynamic size of main section Flex item
- Set static size on footer section Flex item
- Drop epoch progress bar from test page, since it's on home
- Switch to displaying return of `timeUntilNextEpoch()` on test page
- Create `getPeerText()` to generate peers page
- Move peer analysis code from test page to peers page
- Add "Core" section to test page to start work on display
> feat: peers page

- main.go
Create a RTT graph on peers page.
- Add `showPeers` variable to track showing peer stats
- Set `showPeers` to false on return to main
- Set `checkPeers` to true on `p` keypress
- Set `showPeers` to false on `p` keypress
- Add an active "peer" check in main loop to set text on peers page
- Replace `[magenta]` color code with `[fuchsia]` everywhere
- Check for `showPeers` on info page and display appropriate text
- Update stub peerRTT math to give better fake latency spread
- Store "PCT" variables as float32
- Display a RTT peers / percent / graph on peers page
> feat: rtt graph on peers page

- main.go
Provide details on the peers page for each peer.
- Import `sort`
- Clear text and set text to `getPeerText()` in main loop for peers page always
- Add `pingPeers` variable to track collecting peer stats
- Set `pingPeers` to false on `p` keypress
- Restore uptime display on peers page
- Do not show public IP when collecting peer stats
- Create a `Peer` struct to hold peer info
- Use a list of `Peer` for peerStats.RTTresults
- Sort peerStats.RTTresults by RTT
- Display average RTT on peers page
- Display per-peer stats on peers page
> feat: add rtt details to peers page

- config.go
- env.go
- main.go
- node.go
- utils.go
Display core metrics for a block producer on home page.
- Import `runtime`
- Support `CARDANO_BLOCK_PRODUCER` variable to set role
- Create `kesExpiration()` to calculate the KES expiration as time.Time
- Remove usage of `getProtocolParams()` on test page
- Remove "Core" display on test page
- Add "Prometheus metrics" display on test page
- Use correct formatting values on "Mem (Live)" and "Mem (Heap)"
- Display KES information in "Core" display on home page
- Display "Block Production" metrics sourced from Prometheus
- Skip peer analysis on FreeBSD... thanks @reqlez for reporting!
- Refactor public IP address code into `getPublicIP()` in `utils.go`
> feat: display core metrics

- env.go
- internal/config/config.go
- main.go
- node.go
- utils.go
Minor refactoring of the code to move the config.go code into a `config` package, which we put under `internal` to indicate that it's not intended to be used outside this code.
- Move `config.go` to `internal/config` and change package name to `config`
- Import `config` package
- Use `config.LoadConfig()` to load the initial configuration
- Use `config.GetConfig()` to get configuration information
> chore(refactor): move config to an internal package

- main.go
In some cases, our metrics may not be fetched correctly by the time we initialize. Guard around this by checking if our metrics are `nil` before trying to use them.
Closes #76
> fix: crash around setting current epoch

- main.go
Resolves an issue where the Peer Analysis page is scrolled to the bottom, hiding the latency graphs at the top, which is the most likely piece of at a glance information most would want.
- Create `scrollPeers` boolean to track our state
- Set `scrollPeers` to true at the end of peer ping
- Set `ScrollToBeginning()` when `scrollPeers` is true during refresh loop, toggle false
- Set `scrollPeers` to false at beginning of showPeers conditional within `getPeerText()`
Fixes #58
> fix: scroll to beginning of text

- env.go
- internal/config/config.go
- main.go
- node.go
- peers.go
- prometheus.go
- utils.go
Redesign the layout to take advantage of larger screens and our more flexible capabilities.
- Multiple data refresh timers for background data collection
- Process metrics
- Prometheus metrics
- Epoch counter
- Uptime counter
- Peer filter
- Peer pinger 
- Reduce app/screen refresh to 1s
- Remove (i)nfo and (t)est text views
- Replaced lots of magic numbers with new magic numbers for layout (to be improved)
- Rearrange layout into multiple text views and named flex boxes
- More functions
- getEpochProgress / getUptimes
- setRole / getP2P
- filterPeers / pingPeers
- Migrated peer-related functions to peers.go
- Populate a Map and Slice from peer RTT results
> feat: redesign layout

- prometheus.go
Add some handling for the metrics types we don't use, so we can see which are directly supported.
> fix: explicit handling for all prometheus metric types

- .gitignore
- config.yaml.example
- internal/config/config.go
- main.go
- peers.go
- prometheus.go
Read from a provided PID file when running with `amaru` as the binary name to get process metrics.
Otherwise, default to the (unchanged*) `cardano-node` behavior.
*I replaced errors with `continue`. That is changing the behavior, but I assumed that's the preferred behavior.
> Read from a PID file when targeting Amaru
